// ==============================================================================
// Email Service: Resend Integration for Broadcasts & Confirmation Receipts
// (Phase 5: FR-07, FR-08, Extra G)
// ==============================================================================

const RESEND_API_KEY = import.meta.env.VITE_RESEND_API_KEY || import.meta.env.RESEND_API_KEY || '';
const FROM_EMAIL = import.meta.env.VITE_RESEND_FROM_EMAIL || 'onboarding@resend.dev';

const getApiBase = () => {
  if (import.meta.env.VITE_API_URL) return import.meta.env.VITE_API_URL;
  if (typeof window !== 'undefined' && window.location.hostname !== 'localhost' && window.location.hostname !== '127.0.0.1') {
    return '/api/v1';
  }
  return 'http://localhost:3000/api/v1';
};

/**
 * Dispatches an email via backend Resend API to deliver real emails to user inbox (no popups)
 */
export const sendEmail = async ({ to, subject, html, text }) => {
  const payload = {
    to: Array.isArray(to) ? to : [to],
    subject,
    html: html || `<p>${text || subject}</p>`,
    text: text || subject
  };

  // 1. Try sending via backend API (/api/v1/email/send)
  try {
    const apiBase = getApiBase();
    const res = await fetch(`${apiBase}/email/send`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });

    if (res.ok) {
      const data = await res.json().catch(() => ({}));
      console.info('[Email Service] Real email dispatched successfully to:', to, data);
      return { success: true, mode: 'sent_to_inbox', id: data.id };
    }
  } catch (error) {
    console.warn('[Email Service] Primary endpoint unreachable, checking client fallback...', error.message);
  }

  // 2. Direct Resend API Client Fallback if API key is provided directly in client env
  if (RESEND_API_KEY && RESEND_API_KEY !== 'your_key_here') {
    try {
      const directRes = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${RESEND_API_KEY}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          from: FROM_EMAIL.includes('<') ? FROM_EMAIL : `ClubSphere <${FROM_EMAIL}>`,
          to: payload.to,
          subject: payload.subject,
          html: payload.html
        })
      });
      const directData = await directRes.json().catch(() => ({}));
      if (directRes.ok) {
        console.info('[Email Service] Direct Resend dispatched to:', to, directData);
        return { success: true, mode: 'sent_direct_resend', id: directData.id };
      }
    } catch (e) {
      console.warn('[Email Service] Direct Resend attempt failed:', e.message);
    }
  }

  return { success: false, error: 'Email service unavailable or API key not configured' };
};



/**
 * Sends Ticket Booking Confirmation with QR Pass details
 */
export const sendTicketConfirmationEmail = async ({ recipientEmail, attendeeName, eventTitle, ticketId, seat, price }) => {
  const subject = `🎟️ Confirmed: Your Pass for ${eventTitle} (${ticketId})`;
  const html = `
    <div style="font-family: sans-serif; padding: 20px; background-color: #FDF8F0; color: #121212;">
      <h2 style="color: #FF70A6; margin-bottom: 4px;">ClubSphere Event Ticket Pass</h2>
      <p style="font-size: 16px;">Hello <strong>${attendeeName}</strong>,</p>
      <p>Your registration for <strong>${eventTitle}</strong> is confirmed!</p>
      <div style="background: white; border: 2px solid black; padding: 16px; border-radius: 12px; margin: 16px 0;">
        <p><strong>Ticket ID:</strong> ${ticketId}</p>
        <p><strong>Assigned Seat:</strong> ${seat}</p>
        <p><strong>Amount Paid:</strong> ₹${price}</p>
        <p><strong>Status:</strong> Valid / Confirmed Entry</p>
      </div>
      <p>Present your digital QR barcode at the entrance desk for instantaneous check-in.</p>
      <hr style="border: 1px dashed black; margin: 20px 0;" />
      <small style="color: #666;">Generated by ClubSphere Multi-Tenant Student Organization System.</small>
    </div>
  `;

  return sendEmail({ to: recipientEmail, subject, html, text: subject });
};

/**
 * Sends Official Club Domain Login Credentials to User's Personal Email
 */
export const sendClubCredentialsEmail = async ({
  personalEmail,
  userName,
  clubName,
  clubPrefix,
  clubDomainEmail,
  temporaryPassword,
  role = 'student',
  loginUrl
}) => {
  const subject = `🔐 Your Official Login Credentials for ${clubName}`;
  const targetLoginUrl = loginUrl || (typeof window !== 'undefined' ? window.location.origin : 'https://clubsphere-campus-os.vercel.app');

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8" />
      <title>Official ClubSphere Credentials</title>
    </head>
    <body style="margin: 0; padding: 24px; background-color: #FFFDF7; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
      <div style="max-width: 540px; margin: 0 auto; background-color: #FFFFFF; border: 3px solid #121212; border-radius: 16px; overflow: hidden; box-shadow: 6px 6px 0px #121212;">
        
        <!-- Header Banner -->
        <div style="background-color: #FFE853; border-bottom: 3px solid #121212; padding: 20px; text-align: left;">
          <span style="font-size: 11px; font-weight: 900; text-transform: uppercase; letter-spacing: 0.08em; background-color: #121212; color: #FFE853; padding: 4px 8px; border-radius: 4px; display: inline-block; margin-bottom: 8px;">
            Official Club Account Provisioned
          </span>
          <h1 style="margin: 0; font-size: 22px; font-weight: 900; color: #121212;">Welcome to ${clubName}! 🎉</h1>
        </div>

        <!-- Body -->
        <div style="padding: 24px; color: #121212;">
          <p style="font-size: 15px; margin: 0 0 16px; line-height: 1.5;">
            Hello <strong>${userName}</strong>,
          </p>
          <p style="font-size: 14px; margin: 0 0 20px; color: #4B5563; line-height: 1.5;">
            Your registration for <strong>${clubName}</strong> has been confirmed. In accordance with campus data governance and security policies, your personal email is for credential delivery and account recovery.
          </p>

          <!-- Credential Card -->
          <div style="background-color: #F4F4F5; border: 2.5px solid #121212; border-radius: 12px; padding: 18px; margin-bottom: 20px; box-shadow: 3px 3px 0px #121212;">
            <div style="font-size: 11px; font-weight: 900; text-transform: uppercase; color: #71717A; margin-bottom: 6px;">Your Authorized Login Identity:</div>
            
            <div style="margin-bottom: 12px;">
              <div style="font-size: 12px; font-weight: 700; color: #52525B;">Official Club Domain Email:</div>
              <div style="font-size: 17px; font-weight: 900; color: #7C3AED; font-family: monospace; background: #FFFFFF; padding: 8px 12px; border: 1.5px solid #121212; border-radius: 6px; margin-top: 4px;">
                ${clubDomainEmail}
              </div>
            </div>

            <div style="margin-bottom: 12px;">
              <div style="font-size: 12px; font-weight: 700; color: #52525B;">Initial Account Password:</div>
              <div style="font-size: 17px; font-weight: 900; color: #DC2626; font-family: monospace; background: #FFFFFF; padding: 8px 12px; border: 1.5px solid #121212; border-radius: 6px; margin-top: 4px;">
                ${temporaryPassword}
              </div>
            </div>

            <div>
              <div style="font-size: 12px; font-weight: 700; color: #52525B;">Assigned Role:</div>
              <div style="font-size: 13px; font-weight: 800; color: #121212; margin-top: 2px;">
                ${role.toUpperCase()}
              </div>
            </div>
          </div>

          <!-- Policy Alert -->
          <div style="background-color: #FEF3C7; border: 2px solid #F59E0B; border-radius: 8px; padding: 12px; font-size: 12px; font-weight: 700; color: #92400E; margin-bottom: 24px; line-height: 1.4;">
            ⚠️ <strong>Crucial Login Notice:</strong> You <strong>cannot</strong> log in with your personal email (<code>${personalEmail}</code>). The authentication portal will only accept your official club email (<code>${clubDomainEmail}</code>).
          </div>

          <!-- Action Button -->
          <div style="text-align: center;">
            <a href="${targetLoginUrl}" style="display: inline-block; background-color: #121212; color: #FFFFFF; font-size: 15px; font-weight: 900; text-decoration: none; padding: 14px 32px; border-radius: 10px; border: 2px solid #121212; box-shadow: 4px 4px 0px #FFE853;">
              Log in to ClubSphere &rarr;
            </a>
          </div>

          <div style="margin-top: 24px; padding-top: 16px; border-top: 2px dashed #E4E4E7; font-size: 11px; color: #71717A; text-align: center;">
            This security email was delivered to <strong>${personalEmail}</strong> by ClubSphere Campus OS.
          </div>
        </div>
      </div>
    </body>
    </html>
  `;

  return sendEmail({
    to: personalEmail,
    subject,
    html,
    text: `Welcome to ${clubName}! Your official login email is: ${clubDomainEmail}, and password is: ${temporaryPassword}. You must log in using this official club email. Login at: ${targetLoginUrl}`
  });
};

